#声明微服务的端口
server:
  port: 9001

#声明微服务的名称
spring:
  application:
    name: microservice-user
#声明数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.117.39:3306/jsd_20129?useSSL=false&characterEncoding=utf-8
    username: root
    password: 123456

#声明jpd实施正向工程
  jpa:
    show-sql: true    #显示sql语句
    generate-ddl: true    #生成建表语句
    database: mysql        #底层数据库是mybatis数据库