#顶底eureka服务器的端口
server:
  port: 8888
#声明eureka微服务的名称
spring:
  application:
    name: eureka-server

#eureka:
# client:
#  register-with-eureka: false
#  fetch-registry: false
#  service-url:
#    defaultZone: http://192.168.1.112:${server.port}/eureka


#集群版eureka配置
eureka:
 client:
   #将当前的eureka服务注册到另外一个Eureka服务器上（虚拟机）
  register-with-eureka: true
  #同时向另外一台eureka服务器索要信息
  fetch-registry: true
  service-url:
    defaultZone: http://192.168.117.129:8888/eureka
#默默人微服务的注册名称是如下格式
 #计算机名称：微服务名称port
 #如下配置是将计算机名称为IP地址
 instance:
   prefer-ip-address: true